
name: Deploy Infrastructure
on:
  push:
    branches: [master]

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./webapp
    
    steps:
     - name: Checkout Repo
       uses: actions/checkout@v1

    # Install the preferred version of Terraform CLI 
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: 1.1.7